const convUnitsData = {
	"Длина":[
		{"name":"удалить"},
		{"text":"пм","x2":"55","text2":"","name":"пиктометр","conv":"1000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"нм","x2":"55","text2":"","name":"нанометр","conv":"1000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мкм","x2":"55","text2":"","name":"микрометр","conv":"1000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мм","x2":"55","text2":"","name":"милиметр","conv":"1000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"см","x2":"55","text2":"","name":"сантиметр","conv":"100","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дм","x2":"55","text2":"","name":"дециметр","conv":"10","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"м","x2":"45","text2":"","name":"метр","conv":"1","form-for":"enter","form-to":"tometr"},
		{"text":"км","x2":"55","text2":"","name":"киллометр","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"in","x2":"55","text2":"","name":"дюйм","conv":"39.3701","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ft","x2":"55","text2":"","name":"фут","conv":"3.28084","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"yd","x2":"55","text2":"","name":"ярд","conv":"1.09361","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"mi","x2":"55","text2":"","name":"миля","conv":"0.000621371","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"nm","x2":"55","text2":"","name":"морскаямиля","conv":"0.000539957","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"cb","x2":"55","text2":"","name":"кабельтов","conv":"0.00539957","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"lue","x2":"55","text2":"","name":"лье","conv":"0.00018","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"lg","x2":"55","text2":"","name":"лига","conv":"0.000207124","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"an","x2":"55","text2":"","name":"аршин","conv":"1.40625","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"sn","x2":"55","text2":"","name":"сажень","conv":"0.468691","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"vk","x2":"55","text2":"","name":"вершок","conv":"22.4979","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"pyad","x2":"55","text2":"","name":"пядь","conv":"5.6243","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"fg","x2":"55","text2":"","name":"фарлонг","conv":"0.00497096","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ch","x2":"55","text2":"","name":"чейн","conv":"0.0497097","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"rod","x2":"55","text2":"","name":"род","conv":"0.198839","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ph","x2":"55","text2":"","name":"перч","conv":"0.198839","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ell","x2":"55","text2":"","name":"эль","conv":"0.87489","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"cb","x2":"55","text2":"","name":"кубит","conv":"2.18723","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"span","x2":"55","text2":"","name":"спан","conv":"4.37445","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"hand","x2":"55","text2":"","name":"хенд","conv":"9.84252","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"pm","x2":"55","text2":"","name":"палм","conv":"13.1234","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"nl","x2":"55","text2":"","name":"нейл","conv":"17.5","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"fg","x2":"55","text2":"","name":"фингер","conv":"45.4724","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"dg","x2":"55","text2":"","name":"диджит","conv":"52.4934","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"blc","x2":"55","text2":"","name":"барлейкорн","conv":"118.11","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"line","x2":"55","text2":"","name":"линия","conv":"393.701","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"mil","x2":"55","text2":"","name":"мил","conv":"39370.1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"mi","x2":"55","text2":"","name":"микродюйм","conv":"39370078.7","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ps","x2":"55","text2":"","name":"парсек","conv":"0.0000000000000000324078","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ly","x2":"55","text2":"","name":"световойгод","conv":"0.0000000000000001057","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"AU","x2":"55","text2":"","name":"астрономическаяединица","conv":"0.00000000000668459","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"lm","x2":"55","text2":"","name":"световаяминута","conv":"0.000000000055594","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ftm","x2":"55","text2":"","name":"фатом","conv":"0.546807","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"sp","x2":"55","text2":"","name":"спен","conv":"0.4064","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],

	
	"Площадь":[
		{"name":"удалить"},
		{"text":"мм²","x2":"55","text2":"2","name":"кв.миллиметр","conv":"1000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"см²","x2":"55","text2":"2","name":"кв.сантиметр","conv":"10000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дм²","x2":"55","text2":"2","name":"кв.дециметр","conv":"100","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"м²","x2":"45","text2":"2","name":"кв.метр","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"км²","x2":"55","text2":"2","name":"кв.километр","conv":"0.000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"га","x2":"55","text2":"2","name":"гектар","conv":"0.0001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"да","x2":"55","text2":"2","name":"декаар","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"а","x2":"55","text2":"2","name":"ар","conv":"0.01","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"in","x2":"55","text2":"2","name":"кв.дюйм","conv":"1550.0031","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ft","x2":"55","text2":"2","name":"кв.фут","conv":"10.7639","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"yd","x2":"55","text2":"2","name":"кв.ярд","conv":"1.19599","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"mi","x2":"55","text2":"2","name":"кв.миля","conv":"0.0000003861","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ac","x2":"55","text2":"2","name":"акр","conv":"0.000247105","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"in²","x2":"55","text2":"2","name":"кв.дюйм","conv":"1550.0031","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ft²","x2":"55","text2":"2","name":"кв.фут","conv":"10.7639","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"yd²","x2":"55","text2":"2","name":"кв.ярд","conv":"1.19599","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"mi²","x2":"55","text2":"2","name":"кв.миля","conv":"0.0000003861","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
],



	"Объём":[
		{"name":"удалить"},
		{"text":"мм³","x2":"55","text2":"3","name":"куб.миллиметр","conv":"1000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"см³","x2":"55","text2":"3","name":"куб.сантиметр","conv":"1000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дм³","x2":"55","text2":"3","name":"куб.дециметр","conv":"1000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"м³","x2":"45","text2":"3","name":"куб.метр","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"км³","x2":"55","text2":"3","name":"куб.километр","conv":"0.000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л","x2":"45","text2":"3","name":"литр","conv":"1000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мл","x2":"45","text2":"3","name":"миллилитр","conv":"1000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"гал","x2":"45","text2":"3","name":"галлон","conv":"264.172","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"пт","x2":"45","text2":"3","name":"пинта","conv":"2113.38","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кв","x2":"45","text2":"3","name":"кварта","conv":"1056.69","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"бар","x2":"45","text2":"3","name":"баррель","conv":"6.28981","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дюйм³","x2":"45","text2":"3","name":"куб.дюйм","conv":"61023.7","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фут³","x2":"45","text2":"3","name":"куб.фут","conv":"35.3147","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ярд³","x2":"45","text2":"3","name":"куб.ярд","conv":"1.30795","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"см³","x2":"45","text2":"3","name":"куб.сантиметр","conv":"1000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дм³","x2":"45","text2":"3","name":"куб.дециметр","conv":"1000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мм³","x2":"45","text2":"3","name":"куб.миллиметр","conv":"1000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дл","x2":"45","text2":"3","name":"децилитр","conv":"10000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"гл","x2":"45","text2":"3","name":"гектолитр","conv":"10","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мл","x2":"45","text2":"3","name":"мегалитр","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"м³","x2":"45","text2":"3","name":"миллионкуб.метров","conv":"0.000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Гр","x2":"45","text2":"3","name":"грей","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мкГр","x2":"45","text2":"3","name":"микрогрей","conv":"1000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],



	"Вес":[
		{"name":"удалить"},
		{"text":"мг","x2":"45","text2":"","name":"миллиграмм","conv":"1000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"г","x2":"45","text2":"","name":"грамм","conv":"1000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кг","x2":"45","text2":"","name":"килограмм","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"т","x2":"45","text2":"","name":"тонна","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мкг","x2":"45","text2":"","name":"микрограмм","conv":"1000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"нг","x2":"45","text2":"","name":"нанограмм","conv":"1000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"пг","x2":"45","text2":"","name":"пикограмм","conv":"1000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фг","x2":"45","text2":"","name":"фемтограмм","conv":"1000000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"аг","x2":"45","text2":"","name":"аттограмм","conv":"1000000000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дг","x2":"45","text2":"","name":"дециграмм","conv":"10000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"гг","x2":"45","text2":"","name":"гектограмм","conv":"10","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ц","x2":"45","text2":"","name":"центнер","conv":"0.01","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кт","x2":"45","text2":"","name":"килотонна","conv":"0.000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фунт","x2":"45","text2":"","name":"фунт","conv":"2.20462","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"унция","x2":"45","text2":"","name":"унция","conv":"35.274","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"стоун","x2":"45","text2":"","name":"стоун","conv":"0.157473","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"гран","x2":"45","text2":"","name":"гран","conv":"15432.4","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"драхма","x2":"45","text2":"","name":"драхма","conv":"564.383","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"карат","x2":"45","text2":"","name":"карат","conv":"5000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"пуд","x2":"45","text2":"","name":"пуд","conv":"0.0610475","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фр","x2":"45","text2":"","name":"русскийфунт","conv":"2.4419","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"та","x2":"45","text2":"","name":"американскаятонна","conv":"0.00110231","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"тд","x2":"45","text2":"","name":"длиннаятонна","conv":"0.000984207","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"тк","x2":"45","text2":"","name":"короткаятонна","conv":"0.00110231","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ут","x2":"45","text2":"","name":"тройскаяунция","conv":"32.1507","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фт","x2":"45","text2":"","name":"тройскийфунт","conv":"2.67923","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ум","x2":"45","text2":"","name":"метрическаяунция","conv":"35.27396","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кс","x2":"45","text2":"","name":"килограмм-сила","conv":"9.80665","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ка","x2":"45","text2":"","name":"квартер(США)","conv":"0.025","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кб","x2":"45","text2":"","name":"квартер(брит.)","conv":"0.0196841","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"скр","x2":"45","text2":"","name":"скрупул","conv":"7716.18","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"тал","x2":"45","text2":"","name":"талант","conv":"0.000033","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"гм","x2":"45","text2":"","name":"гамма","conv":"1000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"пнн","x2":"45","text2":"","name":"пеннивейт","conv":"643.015","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дт","x2":"45","text2":"","name":"дальтон","conv":"6.02214e+26","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],



	"Энергия":[
		{"name":"удалить"},
		{"text":"Дж","x2":"45","text2":"","name":"джоуль","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кДж","x2":"45","text2":"","name":"килоджоуль","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МДж","x2":"45","text2":"","name":"мегаджоуль","conv":"0.000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ГДж","x2":"45","text2":"","name":"гигаджоуль","conv":"0.000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Вт·ч","x2":"45","text2":"","name":"ватт-час","conv":"0.000277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кВт·ч","x2":"45","text2":"","name":"киловатт-час","conv":"0.000000277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МВт·ч","x2":"45","text2":"","name":"мегаватт-час","conv":"0.000000000277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ГВт·ч","x2":"45","text2":"","name":"гигаватт-час","conv":"0.000000000000277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кал","x2":"45","text2":"","name":"калория","conv":"0.2388458966275","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ккал","x2":"45","text2":"","name":"килокалория","conv":"0.0002388458966275","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Мкал","x2":"45","text2":"","name":"мегакалория","conv":"0.0000002388458966275","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Гкал","x2":"45","text2":"","name":"гигакалория","conv":"0.0000000002388458966275","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"эВ","x2":"45","text2":"","name":"электрон-вольт","conv":"6.242e+18","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кэВ","x2":"45","text2":"","name":"килоэлектрон-вольт","conv":"6.242e+15","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МэВ","x2":"45","text2":"","name":"мегаэлектрон-вольт","conv":"6.242e+12","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ГэВ","x2":"45","text2":"","name":"гигаэлектрон-вольт","conv":"6.242e+9","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ТэВ","x2":"45","text2":"","name":"тераэлектрон-вольт","conv":"6.242e+6","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ПэВ","x2":"45","text2":"","name":"петаэлектрон-вольт","conv":"6.242e+3","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ЭэВ","x2":"45","text2":"","name":"эксаэлектрон-вольт","conv":"6.242","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"БТЕ","x2":"45","text2":"","name":"британскаятепловаяединица","conv":"0.000947817","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кБТЕ","x2":"45","text2":"","name":"килобританскаятепловаяединица","conv":"0.000000947817","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МБТЕ","x2":"45","text2":"","name":"мегабританскаятепловаяединица","conv":"0.000000000947817","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ГБТЕ","x2":"45","text2":"","name":"гигабританскаятепловаяединица","conv":"0.000000000000947817","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Терм","x2":"45","text2":"","name":"терм","conv":"0.00000947817","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.","x2":"45","text2":"","name":"лошадинаясила","conv":"0.0000007457","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кВт","x2":"45","text2":"","name":"киловатт","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МВт","x2":"45","text2":"","name":"мегаватт","conv":"0.000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ГВт","x2":"45","text2":"","name":"гигаватт","conv":"0.000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ТВт","x2":"45","text2":"","name":"тераватт","conv":"0.000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ПВт","x2":"45","text2":"","name":"петаватт","conv":"0.000000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ЭВт","x2":"45","text2":"","name":"эксаватт","conv":"0.000000000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ЗВт","x2":"45","text2":"","name":"зеттаватт","conv":"0.000000000000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ЙВт","x2":"45","text2":"","name":"йоттаватт","conv":"0.000000000000000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],



	"Скорость":[
		{"name":"удалить"},
		{"text":"м/с","x2":"45","text2":"","name":"метрвсекунду","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"км/ч","x2":"45","text2":"","name":"километрвчас","conv":"3.6","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ми/ч","x2":"45","text2":"","name":"милявчас","conv":"2.23694","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"узел","x2":"45","text2":"","name":"узел","conv":"1.94384","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фт/с","x2":"45","text2":"","name":"футвсекунду","conv":"3.28084","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"км/с","x2":"45","text2":"","name":"километрвсекунду","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ми/мин","x2":"45","text2":"","name":"милявминуту","conv":"0.0372823","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"см/с","x2":"45","text2":"","name":"сантиметрвсекунду","conv":"100","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мм/с","x2":"45","text2":"","name":"миллиметрвсекунду","conv":"1000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"миль/ч","x2":"45","text2":"","name":"морскаямилявчас","conv":"1.852","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"миль/мин","x2":"45","text2":"","name":"морскаямилявминуту","conv":"0.0308667","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"миль/с","x2":"45","text2":"","name":"морскаямилявсекунду","conv":"0.000514444","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Мах","x2":"45","text2":"","name":"Мах","conv":"0.00293858","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"скоростьсвета","x2":"45","text2":"","name":"скоростьсвета","conv":"3.33564e-9","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"скоростьзвука","x2":"45","text2":"","name":"скоростьзвука","conv":"0.00293858","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"м/мин","x2":"45","text2":"","name":"метрвминуту","conv":"60","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"км/мин","x2":"45","text2":"","name":"километрвминуту","conv":"0.06","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"км/ч","x2":"45","text2":"","name":"километрвчас","conv":"3.6","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"м/ч","x2":"45","text2":"","name":"метрвчас","conv":"3600","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"см/мин","x2":"45","text2":"","name":"сантиметрвминуту","conv":"6000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мм/мин","x2":"45","text2":"","name":"миллиметрвминуту","conv":"60000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"см/ч","x2":"45","text2":"","name":"сантиметрвчас","conv":"360000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мм/ч","x2":"45","text2":"","name":"миллиметрвчас","conv":"3600000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"миль/ч","x2":"45","text2":"","name":"милявчас","conv":"2.23694","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"миль/мин","x2":"45","text2":"","name":"милявминуту","conv":"0.0372823","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"миль/с","x2":"45","text2":"","name":"милявсекунду","conv":"0.000621371","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ярд/с","x2":"45","text2":"","name":"ярдвсекунду","conv":"1.09361","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ярд/мин","x2":"45","text2":"","name":"ярдвминуту","conv":"65.6168","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ярд/ч","x2":"45","text2":"","name":"ярдвчас","conv":"3937.01","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фут/мин","x2":"45","text2":"","name":"футвминуту","conv":"196.85","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фут/ч","x2":"45","text2":"","name":"футвчас","conv":"11811","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дюйм/с","x2":"45","text2":"","name":"дюймвсекунду","conv":"39.3701","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дюйм/мин","x2":"45","text2":"","name":"дюймвминуту","conv":"2362.2","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дюйм/ч","x2":"45","text2":"","name":"дюймвчас","conv":"141732","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"узел","x2":"45","text2":"","name":"узел","conv":"1.94384","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],



	"Мощность":[
		{"name":"удалить"},
		{"text":"Вт","x2":"45","text2":"","name":"ватт","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кВт","x2":"45","text2":"","name":"киловатт","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МВт","x2":"45","text2":"","name":"мегаватт","conv":"0.000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ГВт","x2":"45","text2":"","name":"гигаватт","conv":"0.000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.","x2":"45","text2":"","name":"лошадинаясила","conv":"0.00134102","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кВт·ч","x2":"45","text2":"","name":"киловатт-час","conv":"0.000277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МВт·ч","x2":"45","text2":"","name":"мегаватт-час","conv":"0.000000277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ГВт·ч","x2":"45","text2":"","name":"гигаватт-час","conv":"0.000000000277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кал/с","x2":"45","text2":"","name":"калориявсекунду","conv":"0.2388458966275","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ккал/с","x2":"45","text2":"","name":"килокалориявсекунду","conv":"0.0002388458966275","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Мкал/с","x2":"45","text2":"","name":"мегакалориявсекунду","conv":"0.0000002388458966275","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Гкал/с","x2":"45","text2":"","name":"гигакалориявсекунду","conv":"0.0000000002388458966275","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"эрг/с","x2":"45","text2":"","name":"эргвсекунду","conv":"10000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"БТЕ/ч","x2":"45","text2":"","name":"британскаятепловаяединицавчас","conv":"3.41214","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кБТЕ/ч","x2":"45","text2":"","name":"килобританскаятепловаяединицавчас","conv":"0.00341214","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МБТЕ/ч","x2":"45","text2":"","name":"мегабританскаятепловаяединицавчас","conv":"0.00000341214","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ГБТЕ/ч","x2":"45","text2":"","name":"гигабританскаятепловаяединицавчас","conv":"0.00000000341214","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Терм/ч","x2":"45","text2":"","name":"термвчас","conv":"0.00000947817","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(м)","x2":"45","text2":"","name":"лошадинаясила(метрическая)","conv":"0.00135962","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(и)","x2":"45","text2":"","name":"лошадинаясила(имперская)","conv":"0.00134102","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(э)","x2":"45","text2":"","name":"лошадинаясила(электрическая)","conv":"0.00134048","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(в)","x2":"45","text2":"","name":"лошадинаясила(водяная)","conv":"0.00134048","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(п)","x2":"45","text2":"","name":"лошадинаясила(паровая)","conv":"0.00134048","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(м)","x2":"45","text2":"","name":"лошадинаясила(метрическая)","conv":"0.00135962","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(и)","x2":"45","text2":"","name":"лошадинаясила(имперская)","conv":"0.00134102","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(э)","x2":"45","text2":"","name":"лошадинаясила(электрическая)","conv":"0.00134048","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(в)","x2":"45","text2":"","name":"лошадинаясила(водяная)","conv":"0.00134048","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(п)","x2":"45","text2":"","name":"лошадинаясила(паровая)","conv":"0.00134048","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(м)","x2":"45","text2":"","name":"лошадинаясила(метрическая)","conv":"0.00135962","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(и)","x2":"45","text2":"","name":"лошадинаясила(имперская)","conv":"0.00134102","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(э)","x2":"45","text2":"","name":"лошадинаясила(электрическая)","conv":"0.00134048","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(в)","x2":"45","text2":"","name":"лошадинаясила(водяная)","conv":"0.00134048","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л.с.(п)","x2":"45","text2":"","name":"лошадинаясила(паровая)","conv":"0.00134048","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],



	"Давление":[
		{"name":"удалить"},
		{"text":"Па","x2":"45","text2":"","name":"паскаль","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кПа","x2":"45","text2":"","name":"килопаскаль","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МПа","x2":"45","text2":"","name":"мегапаскаль","conv":"0.000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ГПа","x2":"45","text2":"","name":"гигапаскаль","conv":"0.000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"бар","x2":"45","text2":"","name":"бар","conv":"0.00001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мбар","x2":"45","text2":"","name":"миллибар","conv":"0.01","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"атм","x2":"45","text2":"","name":"атмосфера","conv":"0.00000986923","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ммрт.ст.","x2":"45","text2":"","name":"миллиметрртутногостолба","conv":"0.00750062","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"смрт.ст.","x2":"45","text2":"","name":"сантиметрртутногостолба","conv":"0.000750062","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ммвод.ст.","x2":"45","text2":"","name":"миллиметрводяногостолба","conv":"0.101972","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"смвод.ст.","x2":"45","text2":"","name":"сантиметрводяногостолба","conv":"0.0101972","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кгс/см²","x2":"45","text2":"","name":"килограмм-силанаквадратныйсантиметр","conv":"0.0000101972","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кгс/м²","x2":"45","text2":"","name":"килограмм-силанаквадратныйметр","conv":"0.101972","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"psi","x2":"45","text2":"","name":"фунтнаквадратныйдюйм","conv":"0.000145038","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"psf","x2":"45","text2":"","name":"фунтнаквадратныйфут","conv":"0.0208854","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Торр","x2":"45","text2":"","name":"торр","conv":"0.00750062","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дин/см²","x2":"45","text2":"","name":"диннаквадратныйсантиметр","conv":"10","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],



	"Углы":[
		{"name":"удалить"},
		{"text":"°","x2":"45","text2":"","name":"градус","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"рад","x2":"45","text2":"","name":"радиан","conv":"0.0174533","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град","x2":"45","text2":"","name":"град","conv":"0.9","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"об","x2":"45","text2":"","name":"оборот","conv":"0.00277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"окт","x2":"45","text2":"","name":"октант","conv":"0.125","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"сек","x2":"45","text2":"","name":"секстант","conv":"0.166667","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"румб","x2":"45","text2":"","name":"румб","conv":"0.111111","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мрад","x2":"45","text2":"","name":"миллирадиан","conv":"17.4533","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"тыс","x2":"45","text2":"","name":"тысячная","conv":"0.0009817477","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.мин","x2":"45","text2":"","name":"градуснаяминута","conv":"60","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.сек","x2":"45","text2":"","name":"градуснаясекунда","conv":"3600","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.дес","x2":"45","text2":"","name":"градуснаядесятая","conv":"10","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.сот","x2":"45","text2":"","name":"градуснаясотая","conv":"100","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.т","x2":"45","text2":"","name":"градуснаятысячная","conv":"1000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.мил","x2":"45","text2":"","name":"градуснаямиллионная","conv":"1000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.мик","x2":"45","text2":"","name":"градуснаямикронная","conv":"1000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.н","x2":"45","text2":"","name":"градуснаянанонная","conv":"1000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.п","x2":"45","text2":"","name":"градуснаяпиконная","conv":"1000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.ф","x2":"45","text2":"","name":"градуснаяфемтонная","conv":"1000000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.а","x2":"45","text2":"","name":"градуснаяаттонная","conv":"1000000000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.зеп","x2":"45","text2":"","name":"градуснаязептонная","conv":"1000000000000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.йок","x2":"45","text2":"","name":"градуснаяйоктонная","conv":"1000000000000000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.р","x2":"45","text2":"","name":"градуснаяронтонная","conv":"1000000000000000000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.к","x2":"45","text2":"","name":"градуснаякветтонная","conv":"1000000000000000000000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.д","x2":"45","text2":"","name":"градуснаядека","conv":"0.1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.г","x2":"45","text2":"","name":"градуснаягекто","conv":"0.01","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.км","x2":"45","text2":"","name":"градуснаякилометр","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.мега","x2":"45","text2":"","name":"градуснаямега","conv":"0.000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.гига","x2":"45","text2":"","name":"градуснаягига","conv":"0.000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.тера","x2":"45","text2":"","name":"градуснаятера","conv":"0.000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.пета","x2":"45","text2":"","name":"градуснаяпета","conv":"0.000000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.эк","x2":"45","text2":"","name":"градуснаяэкса","conv":"0.000000000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.зет","x2":"45","text2":"","name":"градуснаязетта","conv":"0.000000000000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"град.йот","x2":"45","text2":"","name":"градуснаяйотта","conv":"0.000000000000000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],



	"Данные":[
		{"name":"удалить"},
		{"text":"КБ","x2":"45","text2":"","name":"килобайт","conv":"0.000125","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МБ","x2":"45","text2":"","name":"мегабайт","conv":"0.000000125","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ГБ","x2":"45","text2":"","name":"гигабайт","conv":"0.000000000125","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ТБ","x2":"45","text2":"","name":"терабайт","conv":"0.000000000000125","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ПБ","x2":"45","text2":"","name":"петабайт","conv":"0.000000000000000125","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ЭБ","x2":"45","text2":"","name":"эксабайт","conv":"0.000000000000000000125","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ЗБ","x2":"45","text2":"","name":"зеттабайт","conv":"0.000000000000000000000125","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ЙБ","x2":"45","text2":"","name":"йоттабайт","conv":"0.000000000000000000000000125","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"name":"---","text":"---"},
		{"text":"Кбит","x2":"45","text2":"","name":"килобит","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Мбит","x2":"45","text2":"","name":"мегабит","conv":"0.000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Гбит","x2":"45","text2":"","name":"гигабит","conv":"0.000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Тбит","x2":"45","text2":"","name":"терабит","conv":"0.000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Пбит","x2":"45","text2":"","name":"петабит","conv":"0.000000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Эбит","x2":"45","text2":"","name":"эксабит","conv":"0.000000000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Збит","x2":"45","text2":"","name":"зеттабит","conv":"0.000000000000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Йбит","x2":"45","text2":"","name":"йоттабит","conv":"0.000000000000000000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"name":"---","text":"---"},
		{"text":"КиБ","x2":"45","text2":"","name":"кибибайт","conv":"0.0001220703125","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МиБ","x2":"45","text2":"","name":"мебибайт","conv":"0.00000011920928955078125","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ГиБ","x2":"45","text2":"","name":"гибибайт","conv":"0.000000000116415321826934814453125","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ТиБ","x2":"45","text2":"","name":"тебибайт","conv":"0.0000000000001136868377216160297393798828125","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ПиБ","x2":"45","text2":"","name":"пебибайт","conv":"0.0000000000000001110223024625156540429592132568359375","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ЭиБ","x2":"45","text2":"","name":"эксибайт","conv":"0.00000000000000000010842021724855044340096008813381195068359375","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ЗиБ","x2":"45","text2":"","name":"зебибайт","conv":"0.00000000000000000000010587858279163697041427905659734439849853515625","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ЙиБ","x2":"45","text2":"","name":"йобибайт","conv":"0.00000000000000000000000010339757656912742428058285535109043121337890625","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"name":"---","text":"---"},
		{"text":"Кибит","x2":"45","text2":"","name":"кибибит","conv":"0.0009765625","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Мибит","x2":"45","text2":"","name":"мебибит","conv":"0.00000095367431640625","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Гибит","x2":"45","text2":"","name":"гибибит","conv":"0.000000000931322574615478515625","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Тибит","x2":"45","text2":"","name":"тебибит","conv":"0.0000000000009094947017729282379150390625","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Пибит","x2":"45","text2":"","name":"пебибит","conv":"0.00000000000000088817841970012523233890533447265625","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Эибит","x2":"45","text2":"","name":"эксибит","conv":"0.0000000000000000008673617379884035472051713466644287109375","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Зибит","x2":"45","text2":"","name":"зебибит","conv":"0.00000000000000000000084703239295393940255509316921234130859375","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Йибит","x2":"45","text2":"","name":"йобибит","conv":"0.0000000000000000000000008271806125530279931257517039775848388671875","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
],



	"Время":[
		{"name":"удалить"},
		{"text":"с","x2":"45","text2":"","name":"секунда","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мин","x2":"45","text2":"","name":"минута","conv":"0.0166667","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ч","x2":"45","text2":"","name":"час","conv":"0.000277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"д","x2":"45","text2":"","name":"день","conv":"0.0000115741","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"нед","x2":"45","text2":"","name":"неделя","conv":"0.00000165344","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мес","x2":"45","text2":"","name":"месяц","conv":"0.000000380517","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"г","x2":"45","text2":"","name":"год","conv":"0.0000000317098","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дл","x2":"45","text2":"","name":"десятилетие","conv":"0.00000000317098","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"век","x2":"45","text2":"","name":"век","conv":"0.000000000317098","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"тл","x2":"45","text2":"","name":"тысячелетие","conv":"0.0000000000317098","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мс","x2":"45","text2":"","name":"миллисекунда","conv":"1000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мкс","x2":"45","text2":"","name":"микросекунда","conv":"1000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"нс","x2":"45","text2":"","name":"наносекунда","conv":"1000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"пс","x2":"45","text2":"","name":"пикосекунда","conv":"1000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фс","x2":"45","text2":"","name":"фемтосекунда","conv":"1000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ас","x2":"45","text2":"","name":"аттосекунда","conv":"1000000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"зс","x2":"45","text2":"","name":"зептосекунда","conv":"1000000000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"йс","x2":"45","text2":"","name":"йоктосекунда","conv":"1000000000000000000000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],



	"Крутящий момент":[
		{"name":"удалить"},
		{"text":"Н·м","x2":"45","text2":"","name":"ньютон-метр","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кН·м","x2":"45","text2":"","name":"килоньютон-метр","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МН·м","x2":"45","text2":"","name":"меганьютон-метр","conv":"0.000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ГН·м","x2":"45","text2":"","name":"гиганьютон-метр","conv":"0.000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фунт·фут","x2":"45","text2":"","name":"фунт-фут","conv":"0.737562","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фунт·дюйм","x2":"45","text2":"","name":"фунт-дюйм","conv":"8.85075","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кгс·м","x2":"45","text2":"","name":"килограмм-силаметр","conv":"0.101972","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"дин·см","x2":"45","text2":"","name":"дина-сантиметр","conv":"1000000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],



	"Объёмный поток":[
		{"name":"удалить"},
		{"text":"м³/с","x2":"45","text2":"","name":"кубическийметрвсекунду","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"м³/мин","x2":"45","text2":"","name":"кубическийметрвминуту","conv":"0.0166667","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"м³/ч","x2":"45","text2":"","name":"кубическийметрвчас","conv":"0.000277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л/с","x2":"45","text2":"","name":"литрвсекунду","conv":"1000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л/мин","x2":"45","text2":"","name":"литрвминуту","conv":"16.6667","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"л/ч","x2":"45","text2":"","name":"литрвчас","conv":"0.277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"галлон/с","x2":"45","text2":"","name":"галлонвсекунду","conv":"264.172","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"галлон/мин","x2":"45","text2":"","name":"галлонвминуту","conv":"15.8503","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"галлон/ч","x2":"45","text2":"","name":"галлонвчас","conv":"0.264172","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фт³/с","x2":"45","text2":"","name":"кубическийфутвсекунду","conv":"35.3147","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фт³/мин","x2":"45","text2":"","name":"кубическийфутвминуту","conv":"0.588578","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"фт³/ч","x2":"45","text2":"","name":"кубическийфутвчас","conv":"0.0098096","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"баррель/с","x2":"45","text2":"","name":"баррельвсекунду","conv":"6.28981","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"баррель/мин","x2":"45","text2":"","name":"баррельвминуту","conv":"0.1048","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"баррель/ч","x2":"45","text2":"","name":"баррельвчас","conv":"0.001746","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],



	"Расход топлива":[
		{"name":"удалить"},
		{"text":"л/100км","x2":"45","text2":"","name":"литрна100километров","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"км/л","x2":"45","text2":"","name":"километрналитр","conv":"0.01","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ми/гал","x2":"45","text2":"","name":"милянагаллон","conv":"0.425144","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"гал/100миль","x2":"45","text2":"","name":"галлонна100миль","conv":"0.00235215","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"км/гал","x2":"45","text2":"","name":"километрнагаллон","conv":"0.264172","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],



	"Ускорение":[
		{"name":"удалить"},
		{"text":"м/с²","x2":"45","text2":"","name":"метрвсекундувквадрате","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"см/с²","x2":"45","text2":"","name":"сантиметрвсекундувквадрате","conv":"100","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"км/с²","x2":"45","text2":"","name":"километрвсекундувквадрате","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"мм/с²","x2":"45","text2":"","name":"миллиметрвсекундувквадрате","conv":"1000","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ft/s²","x2":"45","text2":"","name":"футвсекундувквадрате","conv":"3.28084","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"in/s²","x2":"45","text2":"","name":"дюймвсекундувквадрате","conv":"39.3701","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"g","x2":"45","text2":"","name":"g(ускорениесвободногопадения)","conv":"0.101972","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],



	"Хранимая энергия":[
		{"name":"удалить"},
		{"text":"Дж","x2":"45","text2":"","name":"джоуль","conv":"1","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кДж","x2":"45","text2":"","name":"килоджоуль","conv":"0.001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МДж","x2":"45","text2":"","name":"мегаджоуль","conv":"0.000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ГДж","x2":"45","text2":"","name":"гигаджоуль","conv":"0.000000001","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кал","x2":"45","text2":"","name":"калория","conv":"0.238846","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"ккал","x2":"45","text2":"","name":"килокалория","conv":"0.000238846","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"Вт·ч","x2":"45","text2":"","name":"ватт-час","conv":"0.000277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"кВт·ч","x2":"45","text2":"","name":"киловатт-час","conv":"0.000000277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"МВт·ч","x2":"45","text2":"","name":"мегаватт-час","conv":"0.000000000277778","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"},
		{"text":"эВ","x2":"45","text2":"","name":"электрон-вольт","conv":"6.242e+18","form-for":"enter/param(conv)","form-to":"param(conv)*tometr"}
	],



	"Температура": [
		{"name": "удалить"},
		{"text": "℃", "x2": "45", "text2": "", "name": "градусЦельсия", "form-for": "enter", "form-to": "tometr"},
		{"text": "℉", "x2": "45", "text2": "", "name": "градусФаренгейта", "form-for": "(enter - 32) * 5 / 9", "form-to": "(tometr * 9 / 5) + 32"},
		{"text": "K", "x2": "45", "text2": "", "name": "Кельвин", "form-for": "enter - 273.15", "form-to": "tometr + 273.15"},
		{"text": "°Ré", "x2": "45", "text2": "", "name": "градусРеомюра", "form-for": "enter * 5 / 4", "form-to": "tometr * 4 / 5"},
		{"text": "°Rø", "x2": "45", "text2": "", "name": "градусРёмера", "form-for": "(enter - 7.5) * 40 / 21", "form-to": "(tometr * 21 / 40) + 7.5"},
		{"text": "°Ra", "x2": "45", "text2": "", "name": "градусРанкина", "form-for": "(enter - 491.67) * 5 / 9", "form-to": "(tometr * 9 / 5) + 491.67"},
		{"text": "°Д", "x2": "45", "text2": "", "name": "градусДелиля", "form-for": "(100 - enter) * 2 / 3", "form-to": "100 - tometr * 3 / 2"},
		{"text": "°H", "x2": "45", "text2": "", "name": "градусГука", "form-for": "enter * 4 / 3", "form-to": "tometr * 3 / 4"},
		{"text": "°Dа", "x2": "45", "text2": "", "name": "градусДальтона", "form-for": "enter * 3 / 1", "form-to": "tometr / 3"},
		{"text": "°N", "x2": "45", "text2": "", "name": "градусНьютона", "form-for": "enter * 33 / 100", "form-to": "tometr * 100 / 33"},
		{"text": "°L", "x2": "45", "text2": "", "name": "лейденскийградус", "form-for": "enter * 5 / 4", "form-to": "tometr * 4 / 5"},
		{"text": "T_P", "x2": "45", "text2": "", "name": "планковскаятемпература", "form-for": "enter * 1.416808e32", "form-to": "tometr / 1.416808e32"}
	],



	"РазмерыОбуви": [
		{"name": "удалить"},
		{"text": "EU Мужск.", "x2": "45", "text2": "", "name": "EU Мужск.", "form-for": "enter", "form-to": "tometr"},
		{"text": "EU Женск.", "x2": "45", "text2": "", "name": "EU Женск.", "form-for": "enter", "form-to": "tometr"},
		{"text": "EU Детск.", "x2": "45", "text2": "", "name": "EU Детск.", "form-for": "enter", "form-to": "tometr"},
		{"text": "US Мужск.", "x2": "45", "text2": "", "name": "US Мужск.", "form-for": "(enter - 31) * 0.5 + 1", "form-to": "(tometr - 1) * 2 + 31"},
		{"text": "US Женск.", "x2": "45", "text2": "", "name": "US Женск.", "form-for": "(enter - 30) * 0.5 + 2", "form-to": "(tometr - 2) * 2 + 30"},
		{"text": "US Детск.", "x2": "45", "text2": "", "name": "US Детск.", "form-for": "(enter * 0.75) + 12", "form-to": "(tometr - 12) / 0.75"},
		{"text": "UK Мужск.", "x2": "45", "text2": "", "name": "UK Мужск.", "form-for": "(enter - 31) * 0.5", "form-to": "(tometr * 2) + 31"},
		{"text": "UK Женск.", "x2": "45", "text2": "", "name": "UK Женск.", "form-for": "(enter - 30) * 0.5 + 1", "form-to": "(tometr - 1) * 2 + 30"},
		{"text": "UK Детск.", "x2": "45", "text2": "", "name": "UK Детск.", "form-for": "(enter * 0.75) + 10", "form-to": "(tometr - 10) / 0.75"},
		{"text": "JP Мужск.", "x2": "45", "text2": "", "name": "JP Мужск.", "form-for": "enter * 1.5 + 18", "form-to": "(tometr - 18) / 1.5"},
		{"text": "JP Женск.", "x2": "45", "text2": "", "name": "JP Женск.", "form-for": "enter * 1.5 + 18", "form-to": "(tometr - 18) / 1.5"},
		{"text": "JP Детск.", "x2": "45", "text2": "", "name": "JP Детск.", "form-for": "enter * 1.5 + 10", "form-to": "(tometr - 10) / 1.5"},
		{"text": "Mondopoint Мужск.", "x2": "45", "text2": "", "name": "Mondopoint Мужск.", "form-for": "enter * 6.67 + 100", "form-to": "(tometr - 100) / 6.67"},
		{"text": "Mondopoint Женск.", "x2": "45", "text2": "", "name": "Mondopoint Женск.", "form-for": "enter * 6.67 + 100", "form-to": "(tometr - 100) / 6.67"},
		{"text": "Mondopoint Детск.", "x2": "45", "text2": "", "name": "Mondopoint Детск.", "form-for": "enter * 6.67 + 85", "form-to": "(tometr - 85) / 6.67"},
		{"text": "RU Мужск.", "x2": "45", "text2": "", "name": "Советский Мужск.", "form-for": "enter", "form-to": "tometr"},
		{"text": "RU Женск.", "x2": "45", "text2": "", "name": "Советский Женск.", "form-for": "enter", "form-to": "tometr"},
		{"text": "RU Детск.", "x2": "45", "text2": "", "name": "Советский етск.", "form-for": "enter", "form-to": "tometr"},
		{"text": "CN Мужск.", "x2": "45", "text2": "", "name": "CN Мужск.", "form-for": "enter - 0", "form-to": "tometr"},
		{"text": "CN Женск.", "x2": "45", "text2": "", "name": "CN Женск.", "form-for": "enter - 0", "form-to": "tometr"},
		{"text": "AU Мужск.", "x2": "45", "text2": "", "name": "Австралийский Мужск.", "form-for": "(enter - 6) * 0.5 + 1", "form-to": "(tometr - 1) * 2 + 6"},
		{"text": "AU Женск.", "x2": "45", "text2": "", "name": "Австралийский Женск.", "form-for": "(enter - 5) * 0.5 + 2", "form-to": "(tometr - 2) * 2 + 5"},
		{"text": "BR Мужск.", "x2": "45", "text2": "", "name": "Бразильский Мужск.", "form-for": "enter - 1", "form-to": "tometr + 1"},
		{"text": "BR Женск.", "x2": "45", "text2": "", "name": "Бразильский Женск.", "form-for": "enter - 1", "form-to": "tometr + 1"},
		{"text": "MX Мужск.", "x2": "45", "text2": "", "name": "Мексиканский Мужск.", "form-for": "enter - 1", "form-to": "tometr + 1"},
		{"text": "MX Женск.", "x2": "45", "text2": "", "name": "Мексиканский Женск.", "form-for": "enter - 1", "form-to": "tometr + 1"},
		{"text": "IN Мужск.", "x2": "45", "text2": "", "name": "Индийский Мужск.", "form-for": "enter - 0", "form-to": "tometr"},
		{"text": "IN Женск.", "x2": "45", "text2": "", "name": "Индийский Женск.", "form-for": "enter - 0", "form-to": "tometr"},
		{"text": "IT Мужск.", "x2": "45", "text2": "", "name": "Итальянский Мужск.", "form-for": "enter", "form-to": "tometr"},
		{"text": "IT Женск.", "x2": "45", "text2": "", "name": "Итальянский Женск.", "form-for": "enter", "form-to": "tometr"},
		{"text": "PH Мужск.", "x2": "45", "text2": "", "name": "Филиппинский Мужск.", "form-for": "enter", "form-to": "tometr"},
		{"text": "PH Женск.", "x2": "45", "text2": "", "name": "Филиппинский Женск.", "form-for": "enter", "form-to": "tometr"},
		{"text": "ZA Мужск.", "x2": "45", "text2": "", "name": "Южноафриканский Мужск.", "form-for": "(enter - 6) * 0.5 + 1", "form-to": "(tometr - 1) * 2 + 6"},
		{"text": "ZA Женск.", "x2": "45", "text2": "", "name": "Южноафриканский Женск.", "form-for": "(enter - 5) * 0.5 + 2", "form-to": "(tometr - 2) * 2 + 5"},
		{"text": "KR Мужск.", "x2": "45", "text2": "", "name": "Корейский Мужск.", "form-for": "enter - 0", "form-to": "tometr"},
		{"text": "KR Женск.", "x2": "45", "text2": "", "name": "Корейский Женск.", "form-for": "enter - 0", "form-to": "tometr"},
		{"text": "VN Мужск.", "x2": "45", "text2": "", "name": "Вьетнамский Мужск.", "form-for": "enter - 0", "form-to": "tometr"},
		{"text": "VN Женск.", "x2": "45", "text2": "", "name": "Вьетнамский Женск.", "form-for": "enter - 0", "form-to": "tometr"}
	],



	"Валюты": [
		{"name":"удалить"},
		{"text":"RUB","x2":"45","text2":"","name":"Российский рубль","form-for":"param(text)-enter","form-to":"val"},
		{"text":"RUP","x2":"45","text2":"","name":"Приднестровский рубль","form-for":"param(text)-enter","form-to":"val"},
		{"text":"UAH","x2":"45","text2":"","name":"Украинская гривна","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MDL","x2":"45","text2":"","name":"Молдавский лей","form-for":"param(text)-enter","form-to":"val"},
		{"name":"---","text":"---"},
		{"text":"USD","x2":"45","text2":"","name":"Доллар США","form-for":"param(text)-enter","form-to":"val"},
		{"text":"EUR","x2":"45","text2":"","name":"Евро","form-for":"param(text)-enter","form-to":"val"},
		{"text":"CNY","x2":"45","text2":"","name":"Китайский юань","form-for":"param(text)-enter","form-to":"val"},
		{"name":"---","text":"---"},
		{"text":"KZT","x2":"45","text2":"","name":"Казахстанский тенге","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BYN","x2":"45","text2":"","name":"Белорусский рубль","form-for":"param(text)-enter","form-to":"val"},
		{"text":"RON","x2":"45","text2":"","name":"Румынский лей","form-for":"param(text)-enter","form-to":"val"},
		{"text":"PLN","x2":"45","text2":"","name":"Польский злотый","form-for":"param(text)-enter","form-to":"val"},
		{"text":"JPY","x2":"45","text2":"","name":"Японская иена","form-for":"param(text)-enter","form-to":"val"},
		{"name":"---","text":"---"},
		{"text":"AED","x2":"45","text2":"","name":"Дирхам ОАЭ","form-for":"param(text)-enter","form-to":"val"},
		{"text":"AFN","x2":"45","text2":"","name":"Афгани","form-for":"param(text)-enter","form-to":"val"},
		{"text":"ALL","x2":"45","text2":"","name":"Лек","form-for":"param(text)-enter","form-to":"val"},
		{"text":"AMD","x2":"45","text2":"","name":"Армянский драм","form-for":"param(text)-enter","form-to":"val"},
		{"text":"ANG","x2":"45","text2":"","name":"Нидерландский антильский гульден","form-for":"param(text)-enter","form-to":"val"},
		{"text":"AOA","x2":"45","text2":"","name":"Кванза","form-for":"param(text)-enter","form-to":"val"},
		{"text":"ARS","x2":"45","text2":"","name":"Аргентинское песо","form-for":"param(text)-enter","form-to":"val"},
		{"text":"AUD","x2":"45","text2":"","name":"Австралийский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"AWG","x2":"45","text2":"","name":"Арубанский флорин","form-for":"param(text)-enter","form-to":"val"},
		{"text":"AZN","x2":"45","text2":"","name":"Азербайджанский манат","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BAM","x2":"45","text2":"","name":"Конвертируемая марка","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BBD","x2":"45","text2":"","name":"Барбадосский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BDT","x2":"45","text2":"","name":"Така","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BGN","x2":"45","text2":"","name":"Болгарский лев","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BHD","x2":"45","text2":"","name":"Бахрейнский динар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BIF","x2":"45","text2":"","name":"Бурундийский франк","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BMD","x2":"45","text2":"","name":"Бермудский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BND","x2":"45","text2":"","name":"Брунейский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BOB","x2":"45","text2":"","name":"Боливиано","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BRL","x2":"45","text2":"","name":"Бразильский реал","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BSD","x2":"45","text2":"","name":"Багамский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BTN","x2":"45","text2":"","name":"Нгултрум","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BWP","x2":"45","text2":"","name":"Пула","form-for":"param(text)-enter","form-to":"val"},
		{"text":"BZD","x2":"45","text2":"","name":"Белизский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"CAD","x2":"45","text2":"","name":"Канадский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"CDF","x2":"45","text2":"","name":"Конголезский франк","form-for":"param(text)-enter","form-to":"val"},
		{"text":"CHF","x2":"45","text2":"","name":"Швейцарский франк","form-for":"param(text)-enter","form-to":"val"},
		{"text":"CLP","x2":"45","text2":"","name":"Чилийское песо","form-for":"param(text)-enter","form-to":"val"},
		{"text":"COP","x2":"45","text2":"","name":"Колумбийское песо","form-for":"param(text)-enter","form-to":"val"},
		{"text":"CRC","x2":"45","text2":"","name":"Коста-риканский колон","form-for":"param(text)-enter","form-to":"val"},
		{"text":"CUP","x2":"45","text2":"","name":"Кубинское песо","form-for":"param(text)-enter","form-to":"val"},
		{"text":"CVE","x2":"45","text2":"","name":"Эскудо Кабо-Верде","form-for":"param(text)-enter","form-to":"val"},
		{"text":"CZK","x2":"45","text2":"","name":"Чешская крона","form-for":"param(text)-enter","form-to":"val"},
		{"text":"DJF","x2":"45","text2":"","name":"Джибутийский франк","form-for":"param(text)-enter","form-to":"val"},
		{"text":"DKK","x2":"45","text2":"","name":"Датская крона","form-for":"param(text)-enter","form-to":"val"},
		{"text":"DOP","x2":"45","text2":"","name":"Доминиканское песо","form-for":"param(text)-enter","form-to":"val"},
		{"text":"DZD","x2":"45","text2":"","name":"Алжирский динар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"EGP","x2":"45","text2":"","name":"Египетский фунт","form-for":"param(text)-enter","form-to":"val"},
		{"text":"ERN","x2":"45","text2":"","name":"Накфа","form-for":"param(text)-enter","form-to":"val"},
		{"text":"ETB","x2":"45","text2":"","name":"Эфиопский быр","form-for":"param(text)-enter","form-to":"val"},
		{"text":"FJD","x2":"45","text2":"","name":"Фиджийский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"FKP","x2":"45","text2":"","name":"Фунт Фолклендских островов","form-for":"param(text)-enter","form-to":"val"},
		{"text":"FOK","x2":"45","text2":"","name":"Фарерская крона","form-for":"param(text)-enter","form-to":"val"},
		{"text":"GBP","x2":"45","text2":"","name":"Британский фунт","form-for":"param(text)-enter","form-to":"val"},
		{"text":"GEL","x2":"45","text2":"","name":"Грузинский лари","form-for":"param(text)-enter","form-to":"val"},
		{"text":"GGP","x2":"45","text2":"","name":"Гернсийский фунт","form-for":"param(text)-enter","form-to":"val"},
		{"text":"GHS","x2":"45","text2":"","name":"Ганский седи","form-for":"param(text)-enter","form-to":"val"},
		{"text":"GIP","x2":"45","text2":"","name":"Гибралтарский фунт","form-for":"param(text)-enter","form-to":"val"},
		{"text":"GMD","x2":"45","text2":"","name":"Даласи","form-for":"param(text)-enter","form-to":"val"},
		{"text":"GNF","x2":"45","text2":"","name":"Гвинейский франк","form-for":"param(text)-enter","form-to":"val"},
		{"text":"GTQ","x2":"45","text2":"","name":"Кетсаль","form-for":"param(text)-enter","form-to":"val"},
		{"text":"GYD","x2":"45","text2":"","name":"Гайанский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"HKD","x2":"45","text2":"","name":"Гонконгский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"HNL","x2":"45","text2":"","name":"Лемпира","form-for":"param(text)-enter","form-to":"val"},
		{"text":"HRK","x2":"45","text2":"","name":"Хорватская куна","form-for":"param(text)-enter","form-to":"val"},
		{"text":"HTG","x2":"45","text2":"","name":"Гурд","form-for":"param(text)-enter","form-to":"val"},
		{"text":"HUF","x2":"45","text2":"","name":"Венгерский форинт","form-for":"param(text)-enter","form-to":"val"},
		{"text":"IDR","x2":"45","text2":"","name":"Индонезийская рупия","form-for":"param(text)-enter","form-to":"val"},
		{"text":"ILS","x2":"45","text2":"","name":"Новый израильский шекель","form-for":"param(text)-enter","form-to":"val"},
		{"text":"IMP","x2":"45","text2":"","name":"Остров Мэн фунт","form-for":"param(text)-enter","form-to":"val"},
		{"text":"INR","x2":"45","text2":"","name":"Индийская рупия","form-for":"param(text)-enter","form-to":"val"},
		{"text":"IQD","x2":"45","text2":"","name":"Иракский динар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"IRR","x2":"45","text2":"","name":"Иранский риал","form-for":"param(text)-enter","form-to":"val"},
		{"text":"ISK","x2":"45","text2":"","name":"Исландская крона","form-for":"param(text)-enter","form-to":"val"},
		{"text":"JEP","x2":"45","text2":"","name":"Джерсийский фунт","form-for":"param(text)-enter","form-to":"val"},
		{"text":"JMD","x2":"45","text2":"","name":"Ямайский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"JOD","x2":"45","text2":"","name":"Иорданский динар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"KES","x2":"45","text2":"","name":"Кенийский шиллинг","form-for":"param(text)-enter","form-to":"val"},
		{"text":"KGS","x2":"45","text2":"","name":"Киргизский сом","form-for":"param(text)-enter","form-to":"val"},
		{"text":"KHR","x2":"45","text2":"","name":"Камбоджийский риель","form-for":"param(text)-enter","form-to":"val"},
		{"text":"KID","x2":"45","text2":"","name":"Доллар Кирибати","form-for":"param(text)-enter","form-to":"val"},
		{"text":"KMF","x2":"45","text2":"","name":"Коморский франк","form-for":"param(text)-enter","form-to":"val"},
		{"text":"KRW","x2":"45","text2":"","name":"Южнокорейская вона","form-for":"param(text)-enter","form-to":"val"},
		{"text":"KWD","x2":"45","text2":"","name":"Кувейтский динар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"KYD","x2":"45","text2":"","name":"Доллар Каймановых островов","form-for":"param(text)-enter","form-to":"val"},
		{"text":"LAK","x2":"45","text2":"","name":"Лаосский кип","form-for":"param(text)-enter","form-to":"val"},
		{"text":"LBP","x2":"45","text2":"","name":"Ливанский фунт","form-for":"param(text)-enter","form-to":"val"},
		{"text":"LKR","x2":"45","text2":"","name":"Шри-ланкийская рупия","form-for":"param(text)-enter","form-to":"val"},
		{"text":"LRD","x2":"45","text2":"","name":"Либерийский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"LSL","x2":"45","text2":"","name":"Лоти","form-for":"param(text)-enter","form-to":"val"},
		{"text":"LYD","x2":"45","text2":"","name":"Ливийский динар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MAD","x2":"45","text2":"","name":"Марокканский дирхам","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MGA","x2":"45","text2":"","name":"Малагасийский ариари","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MKD","x2":"45","text2":"","name":"Македонский денар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MMK","x2":"45","text2":"","name":"Мьянманский кьят","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MNT","x2":"45","text2":"","name":"Монгольский тугрик","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MOP","x2":"45","text2":"","name":"Патака Макао","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MRU","x2":"45","text2":"","name":"Мавританская угия","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MUR","x2":"45","text2":"","name":"Маврикийская рупия","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MVR","x2":"45","text2":"","name":"Мальдивская руфия","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MWK","x2":"45","text2":"","name":"Малавийская квача","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MXN","x2":"45","text2":"","name":"Мексиканское песо","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MYR","x2":"45","text2":"","name":"Малайзийский ринггит","form-for":"param(text)-enter","form-to":"val"},
		{"text":"MZN","x2":"45","text2":"","name":"Мозамбикский метикал","form-for":"param(text)-enter","form-to":"val"},
		{"text":"NAD","x2":"45","text2":"","name":"Намибийский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"NGN","x2":"45","text2":"","name":"Нигерийская найра","form-for":"param(text)-enter","form-to":"val"},
		{"text":"NIO","x2":"45","text2":"","name":"Никарагуанская кордоба","form-for":"param(text)-enter","form-to":"val"},
		{"text":"NOK","x2":"45","text2":"","name":"Норвежская крона","form-for":"param(text)-enter","form-to":"val"},
		{"text":"NPR","x2":"45","text2":"","name":"Непальская рупия","form-for":"param(text)-enter","form-to":"val"},
		{"text":"NZD","x2":"45","text2":"","name":"Новозеландский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"OMR","x2":"45","text2":"","name":"Оманский риал","form-for":"param(text)-enter","form-to":"val"},
		{"text":"PAB","x2":"45","text2":"","name":"Бальбоа","form-for":"param(text)-enter","form-to":"val"},
		{"text":"PEN","x2":"45","text2":"","name":"Перуанский соль","form-for":"param(text)-enter","form-to":"val"},
		{"text":"PGK","x2":"45","text2":"","name":"Кина","form-for":"param(text)-enter","form-to":"val"},
		{"text":"PHP","x2":"45","text2":"","name":"Филиппинское песо","form-for":"param(text)-enter","form-to":"val"},
		{"text":"PKR","x2":"45","text2":"","name":"Пакистанская рупия","form-for":"param(text)-enter","form-to":"val"},
		{"text":"PYG","x2":"45","text2":"","name":"Парагвайский гуарани","form-for":"param(text)-enter","form-to":"val"},
		{"text":"QAR","x2":"45","text2":"","name":"Катарский риал","form-for":"param(text)-enter","form-to":"val"},
		{"text":"RSD","x2":"45","text2":"","name":"Сербский динар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"RWF","x2":"45","text2":"","name":"Руандийский франк","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SAR","x2":"45","text2":"","name":"Саудовский риал","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SBD","x2":"45","text2":"","name":"Доллар Соломоновых островов","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SCR","x2":"45","text2":"","name":"Сейшельская рупия","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SDG","x2":"45","text2":"","name":"Суданский фунт","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SEK","x2":"45","text2":"","name":"Шведская крона","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SGD","x2":"45","text2":"","name":"Сингапурский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SHP","x2":"45","text2":"","name":"Фунт Святой Елены","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SLE","x2":"45","text2":"","name":"Сьерра-леонский леоне","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SLL","x2":"45","text2":"","name":"Сьерра-леонский леоне","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SOS","x2":"45","text2":"","name":"Сомалийский шиллинг","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SRD","x2":"45","text2":"","name":"Суринамский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SSP","x2":"45","text2":"","name":"Южносуданский фунт","form-for":"param(text)-enter","form-to":"val"},
		{"text":"STN","x2":"45","text2":"","name":"Добра","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SVC","x2":"45","text2":"","name":"Сальвадорский колон","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SYP","x2":"45","text2":"","name":"Сирийский фунт","form-for":"param(text)-enter","form-to":"val"},
		{"text":"SZL","x2":"45","text2":"","name":"Свазилендский лилангени","form-for":"param(text)-enter","form-to":"val"},
		{"text":"THB","x2":"45","text2":"","name":"Таиландский бат","form-for":"param(text)-enter","form-to":"val"},
		{"text":"TJS","x2":"45","text2":"","name":"Таджикский сомони","form-for":"param(text)-enter","form-to":"val"},
		{"text":"TMT","x2":"45","text2":"","name":"Туркменский манат","form-for":"param(text)-enter","form-to":"val"},
		{"text":"TND","x2":"45","text2":"","name":"Тунисский динар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"TOP","x2":"45","text2":"","name":"Паанга","form-for":"param(text)-enter","form-to":"val"},
		{"text":"TRY","x2":"45","text2":"","name":"Турецкая лира","form-for":"param(text)-enter","form-to":"val"},
		{"text":"TTD","x2":"45","text2":"","name":"Доллар Тринидада и Тобаго","form-for":"param(text)-enter","form-to":"val"},
		{"text":"TVD","x2":"45","text2":"","name":"Тувалуанский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"TWD","x2":"45","text2":"","name":"Тайваньский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"TZS","x2":"45","text2":"","name":"Танзанийский шиллинг","form-for":"param(text)-enter","form-to":"val"},
		{"text":"UGX","x2":"45","text2":"","name":"Угандийский шиллинг","form-for":"param(text)-enter","form-to":"val"},
		{"text":"UYU","x2":"45","text2":"","name":"Уругвайское песо","form-for":"param(text)-enter","form-to":"val"},
		{"text":"UZS","x2":"45","text2":"","name":"Узбекский сум","form-for":"param(text)-enter","form-to":"val"},
		{"text":"VES","x2":"45","text2":"","name":"Венесуэльский боливар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"VND","x2":"45","text2":"","name":"Вьетнамский донг","form-for":"param(text)-enter","form-to":"val"},
		{"text":"VUV","x2":"45","text2":"","name":"Вату","form-for":"param(text)-enter","form-to":"val"},
		{"text":"WST","x2":"45","text2":"","name":"Тала","form-for":"param(text)-enter","form-to":"val"},
		{"text":"XAF","x2":"45","text2":"","name":"Центральноафриканский франк","form-for":"param(text)-enter","form-to":"val"},
		{"text":"XCD","x2":"45","text2":"","name":"Восточно-карибский доллар","form-for":"param(text)-enter","form-to":"val"},
		{"text":"XOF","x2":"45","text2":"","name":"Западноафриканский франк","form-for":"param(text)-enter","form-to":"val"},
		{"text":"XPF","x2":"45","text2":"","name":"Французский тихоокеанский франк","form-for":"param(text)-enter","form-to":"val"},
		{"text":"YER","x2":"45","text2":"","name":"Йеменский риал","form-for":"param(text)-enter","form-to":"val"},
		{"text":"ZAR","x2":"45","text2":"","name":"Южноафриканский рэнд","form-for":"param(text)-enter","form-to":"val"},
		{"text":"ZMW","x2":"45","text2":"","name":"Замбийская квача","form-for":"param(text)-enter","form-to":"val"},
		{"text":"ZWL","x2":"45","text2":"","name":"Зимбабвийский доллар","form-for":"param(text)-enter","form-to":"val"} 
	],



	"Система счисления":[
		{"name":"удалить"},
		{"text":"BIN","x2":"45","text2":"","name":"Двоичная","conv":"2","form-for":"sysf(enter)(2)","form-to":"syst(tometr)(2)"},
		{"text":"DEC","x2":"45","text2":"","name":"Десятичная","conv":"10","form-for":"enter","form-to":"tometr"},
		{"text":"HEX","x2":"45","text2":"","name":"Шестнадцатиричная","conv":"16","form-for":"enter","form-to":"tometr"},
		{"name":"---","text":"---"},
		{"text":"OCT","x2":"45","text2":"","name":"Восьмиричная","conv":"8","form-for":"enter","form-to":"tometr"},
		{"text":"DUO","x2":"45","text2":"","name":"Двенадцатиричная","conv":"12","form-for":"enter","form-to":"tometr"},
		{"text":"TRI","x2":"45","text2":"","name":"Тридцатишестиричная","conv":"36","form-for":"enter","form-to":"tometr"},
		{"name":"---","text":"---"},
		{"text":"3","x2":"45","text2":"","name":"Троичная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"4","x2":"45","text2":"","name":"Квадричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"5","x2":"45","text2":"","name":"Пятичная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"6","x2":"45","text2":"","name":"Шестичная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"7","x2":"45","text2":"","name":"Семичная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"9","x2":"45","text2":"","name":"Девятиричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"11","x2":"45","text2":"","name":"Одинадцатиричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"13","x2":"45","text2":"","name":"Тринадцатичная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"14","x2":"45","text2":"","name":"Четырнадцатичная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"15","x2":"45","text2":"","name":"Пятнадцатичная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"17","x2":"45","text2":"","name":"Семнадцатиричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"18","x2":"45","text2":"","name":"Восьмидесятиричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"19","x2":"45","text2":"","name":"Девятнадцатичная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"20","x2":"45","text2":"","name":"Двадцатичная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"21","x2":"45","text2":"","name":"Двадцатиодноричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"22","x2":"45","text2":"","name":"Двадцатидвухричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"23","x2":"45","text2":"","name":"Nричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"24","x2":"45","text2":"","name":"Nричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"25","x2":"45","text2":"","name":"Nричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"26","x2":"45","text2":"","name":"Nричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"27","x2":"45","text2":"","name":"Nричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"28","x2":"45","text2":"","name":"Nричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"29","x2":"45","text2":"","name":"Nричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"30","x2":"45","text2":"","name":"Nричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"31","x2":"45","text2":"","name":"Nричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"32","x2":"45","text2":"","name":"Nричная","conv":"20","form-for":"enter","form-to":"tometr"},
		{"text":"33","x2":"45","text2":"","name":"Nричная","conv":"20","form-for":"enter","form-to":"tometr"}
	]
};